change-log-file=src/main/resources/db/changelog/db-changelog.xml
output-changelog-file=src/main/resources/db/changelog/liquibase-output.xml
url=jdbc:postgresql://localhost:54320/postgres
username=postgres
password=postgres
driver-class-name=org.postgresql.Driver